// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var NodeEmoji = require("node-emoji");

function getEmoji(emoji) {
  return NodeEmoji.get(emoji) + "  ";
}

exports.getEmoji = getEmoji;
/* node-emoji Not a pure module */
