// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var NodeEmoji = require("node-emoji");

function getEmoji(emoji) {
  return NodeEmoji.get(emoji) + "  ";
}

var altCodeDirectionalNonTerminal = ( "├─ " );

var altCodeDirectional = ( "└─ " );

exports.getEmoji                      = getEmoji;
exports.altCodeDirectionalNonTerminal = altCodeDirectionalNonTerminal;
exports.altCodeDirectional            = altCodeDirectional;
/* altCodeDirectionalNonTerminal Not a pure module */
