// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var GenericBindings$ReasonTemplate = require("./genericBindings.js");

var use = [/* true */1];

function config() {
  var match = use[0];
  if (match !== 0) {
    return GenericBindings$ReasonTemplate.getEmoji("truck");
  } else {
    return "";
  }
}

function validate() {
  var match = use[0];
  if (match !== 0) {
    return GenericBindings$ReasonTemplate.getEmoji("open_file_folder");
  } else {
    return "";
  }
}

function linking() {
  var match = use[0];
  if (match !== 0) {
    return GenericBindings$ReasonTemplate.getEmoji("link");
  } else {
    return "";
  }
}

function postinstall() {
  var match = use[0];
  if (match !== 0) {
    return GenericBindings$ReasonTemplate.getEmoji("nut_and_bolt");
  } else {
    return "";
  }
}

function failure() {
  var match = use[0];
  if (match !== 0) {
    return GenericBindings$ReasonTemplate.getEmoji("no_entry_sign");
  } else {
    return "";
  }
}

function success() {
  var match = use[0];
  if (match !== 0) {
    return GenericBindings$ReasonTemplate.getEmoji("sparkles");
  } else {
    return "";
  }
}

var Emojis = /* module */[
  /* use */use,
  /* config */config,
  /* validate */validate,
  /* linking */linking,
  /* postinstall */postinstall,
  /* failure */failure,
  /* success */success
];

exports.Emojis = Emojis;
/* GenericBindings-ReasonTemplate Not a pure module */
