// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Init$ReasonTemplate = require("./init.js");

function handleInit() {
  return Init$ReasonTemplate.InitCommand[/* main */8];
}

exports.handleInit = handleInit;
/* Init-ReasonTemplate Not a pure module */
