// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Init$ReasonTemplate = require("./init.js");

function handleInit() {
  return Init$ReasonTemplate.handle;
}

exports.handleInit = handleInit;
/* No side effect */
