// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function handle(alias, directory) {
  return "handle " + (alias + (" -> " + directory));
}

exports.handle = handle;
/* No side effect */
