// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Link$ReasonTemplate   = require("./link.bs.js");
var Setup$ReasonTemplate  = require("./setup.bs.js");
var Config$ReasonTemplate = require("./config.bs.js");
var Linter$ReasonTemplate = require("./linter.bs.js");

function handleSetup() {
  return Setup$ReasonTemplate.main;
}

function handleLink() {
  return Link$ReasonTemplate.main;
}

function handleLinter() {
  return Linter$ReasonTemplate.main;
}

function handleConfig() {
  return Config$ReasonTemplate.main;
}

exports.handleSetup  = handleSetup;
exports.handleLink   = handleLink;
exports.handleLinter = handleLinter;
exports.handleConfig = handleConfig;
/* Link-ReasonTemplate Not a pure module */
