// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var MyModule$ReasonTemplate = require("./myModule.js");

var coreAttribute = "Core attribute and " + MyModule$ReasonTemplate.someAttribute;

exports.coreAttribute = coreAttribute;
/* No side effect */
