// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List                    = require("bs-platform/lib/js/list.js");
var MyModule$ReasonTemplate = require("./myModule.js");

var coreAttribute = "Core attribute with " + MyModule$ReasonTemplate.someAttribute;

function main() {
  List.map((function (x) {
          console.log(x);
          return /* () */0;
        }), /* :: */[
        "a",
        /* :: */[
          "b",
          /* :: */[
            "c",
            /* :: */[
              "d",
              /* [] */0
            ]
          ]
        ]
      ]);
  return /* () */0;
}

function parse(argv) {
  List.map((function (x) {
          console.log(x);
          return /* () */0;
        }), argv);
  return /* () */0;
}

var Shell = /* module */[
  /* test */"test",
  /* main */main,
  /* parse */parse
];

function add1(n) {
  return n + 1 | 0;
}

exports.coreAttribute = coreAttribute;
exports.Shell         = Shell;
exports.add1          = add1;
/* No side effect */
