// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var MyModule$ReasonTemplate = require("./myModule.js");

var coreAttribute = "Core attribute with " + MyModule$ReasonTemplate.someAttribute;

function main(n) {
  return n + 1 | 0;
}

var Shell = /* module */[
  /* test */"test",
  /* main */main
];

function add1(n) {
  return n + 1 | 0;
}

exports.coreAttribute = coreAttribute;
exports.Shell         = Shell;
exports.add1          = add1;
/* No side effect */
