// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var MyModule$ReasonTemplate = require("./myModule.js");

var coreAttribute = "Core attribute with " + MyModule$ReasonTemplate.someAttribute;

exports.coreAttribute = coreAttribute;
/* No side effect */
