// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Setup$ReasonTemplate = require("./setup.js");

function handleSetup() {
  return Setup$ReasonTemplate.main;
}

exports.handleSetup = handleSetup;
/* Setup-ReasonTemplate Not a pure module */
