// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Link$ReasonTemplate  = require("./link.js");
var Setup$ReasonTemplate = require("./setup.js");

function handleSetup() {
  return Setup$ReasonTemplate.main;
}

function handleLink() {
  return Link$ReasonTemplate.main;
}

exports.handleSetup = handleSetup;
exports.handleLink  = handleLink;
/* Link-ReasonTemplate Not a pure module */
